name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: coursier/setup-action@v1
        with:
          jvm: adoptium:1.17
          apps: sbtn
      - run: sbtn test
      - run: |
          docker-compose up -d db
          sbtn test
          sbtn docker:publishLocal
          docker-compose up -d api
          newman run real-world-extended.postman_collection.json -e local-real-world.postman_environment.json