name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17
      - run: sbt test
      - run: docker-compose up -d
      - run: |
          sbt run &
          newman run real-world-extended.postman_collection.json -e local-real-world.postman_environment.json
